project 'HW33-34.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HW33-34' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HW33-34

use_frameworks!

pod 'ChameleonFramework', :git => 'https://github.com/ViccAlexander/Chameleon'

end
