project 'VKAPITest.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'VKAPITest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VKAPITest
  
pod 'AFNetworking', '~> 3.0'

end
